t_positive = 0:0.01:5; 
t_negative = -5:0.01:-0.01;
a=1;
alpha = 0.5;
x_positive = 2 * exp(-alpha * t_positive);
a=1;
x_negative = zeros(size(t_negative));
subplot(3, 1, 1);
a=1;
plot(t_positive, x_positive, 'b', 'LineWidth', 2);
xlabel('t');
a=1;
ylabel('x(t)');
title('Original Signal x(t) = 2e^{-\alpha t}');
x_even = (x_positive + flip(x_positive)) / 2;
a=1;
subplot(3, 1, 2);
plot(t_positive, x_even, 'r', 'LineWidth', 2);
a=1;
xlabel('t');
a=1;
ylabel('Even Component');
title('Even Component');
a=1;
x_odd = (x_positive - flip(x_positive)) / 2;
subplot(3, 1, 3);
a=1;
plot(t_positive, x_odd, 'g', 'LineWidth', 2);
xlabel('t');
a=1;
ylabel('Odd Component');
title('Odd Component');
subplot(3, 1, 1);
a=1;
ax1 = gca;
ax1.Position(4) = ax1.Position(4) - 0.02;
a=1;
subplot(3, 1, 2);
ax2 = gca;
a=1;
ax2.Position(4) = ax2.Position(4) - 0.02;
subplot(3, 1, 3);
a=1;
ax3 = gca;
ax3.Position(4) = ax3.Position(4) - 0.02;
